#APPLICATION VARIABLES
APP:
  LOGDIR : './/logs//' #Directory for log files
  LOGGING_LEVEL : 'INFO' #Valid values INFO, DEBUG, ERROR, WARN, FATAL, CRITICAL
  LOG_RETENTION : 90 #Number of days to retain logs in log directory

#TASKS TO RUN (True or False)
TASKS:
  PROVISION_USERS : True #Adds Users To Tableau Cloud as Unlicenced
  ADD_USER_GROUP_MEMBERS : True #Adds newly provisioned users to group defined by GLSI_GROUP_NAME
  SET_USERS_SITEROLE_AS_VIEWER : False #Sets newly provisioned user roles to viewer (rather than unlicensed)
  REMOVE_USER_GROUP_MEMBERS : True #Removes users in the leavers table from group defined by GLSI_GROUP_NAME
  SET_USERS_SITEROLE_AS_UNLICENSED : True #Sets users in the leaves table as unlicensed
  ADD_UNLICENSED_USER_GROUP_MEMBERS : False #Adds users in the leavers table back into GLSI_GROUP_NAME in case they log back into Tableau
  REMOVE_USERS : False #Removes users from Tableau Cloud (only works for users that do not own content)

#TABLEAU ONLINE AUTHENTICATION VARIABLES
TABLEAU:
  TABLEAU_USER : '<YOUR TABLEAU USER NAME>'
  TABLEAU_PAT : '<YOUR PAT TOKEN>'
  TABLEAU_SITE : '<YOUR TABLEAU SITE NAME>'
  TABLEAU_SERVER : 'https://prod-uk-a.online.tableau.com'
  TABLEAU_SERVER_VERSION : '3.16'
  GLSI_GROUP_NAME: '<YOUR TABLEAU GROUP NAME>' #Group with Grant User Role On Sign In Enabled
  AUTH_SETTING: 'SAML' #Set to SAML or ServerDefault for Tableau Authentication

#SNOWFLAKE AUTHENTICATION VARIABLES
SNOWFLAKE:
  USER  : '<YOUR SNOWFLAKE USER NAME>'
  PASSWORD  : '<YOUR SNOWFLAKE PASSWORD>'
  ACCOUNT  : '<YOUR SNOWFLAKE ACCOUNT>'
  WAREHOUSE  : '<YOUR SNOWFLAKE DW NAME>'
  DATABASE  : '<YOUR SNOWFLAKE DATABASE>'
  SCHEMA  : '<YOUR SNOWFLAKE SCHEMA>'
  JOINERS_TABLE : '<YOUR SNOWFLAKE JOINERS TABLE>' #Must include column "Email Address"
  LEAVERS_TABLE : '<YOUR SNOWFLAKE LEAVERS TABLE>' #Must include column "Email Address"

#EMAIL NOTIFICATION VARIABLES
EMAIL:
  EMAIL_SUBJECT  : '***Tableau Cloud user provisioning logs***'  # subject
  EMAIL_BODY  : "This is an automated message sent by the Tableau user provisioning script. \n\n
                 The script ran but some users were not added/removed successfully. \n\n
                 Please review the attached log file for details. \n\n"  # body
  EMAIL_FROM  : 'info@tableauscript.com'  # from
  EMAIL_TO : ['<YOUR EMAIL ADDRESS>']  # to
  EMAIL_HOST : '<YOUR SMTP SERVER>'
  EMAIL_PORT : 587
  EMAIL_HOST_USER : '<YOUR EMAIL HOST USER ADDRESS>'
  EMAIL_HOST_PASSWORD : '<YOUR EMAIL HOST PASSWORD>'
